# Generated by Django 6.0.6 on 2026-06-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, null=True)),
                ('nested_fields', models.JSONField(blank=True, default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='admin_pages.page')),
            ],
        ),
    ]
