# Generated by Django 6.0.6 on 2026-06-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RemoveField(
            model_name='jobrequirement',
            name='job',
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='jobPosting',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='JobBenefit',
        ),
        migrations.DeleteModel(
            name='JobDepartment',
        ),
        migrations.DeleteModel(
            name='JobLocation',
        ),
        migrations.DeleteModel(
            name='JobRequirement',
        ),
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
