# Generated by Django 6.0.6 on 2026-06-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_jobs', '0002_alter_jobposting_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='experience',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
