# Generated by Django 6.0.6 on 2026-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_jobs', '0003_jobposting_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
