# Generated by Django 6.0.6 on 2026-06-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
