# Generated by Django 6.0.6 on 2026-06-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_contact', '0002_alter_contactsubmission_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
