# Generated by Django 6.0.6 on 2026-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_contact', '0003_contactsubmission_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('accepted_all', models.BooleanField(default=True)),
                ('analytics_accepted', models.BooleanField(default=True)),
                ('marketing_accepted', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('purpose_of_visit', models.CharField(blank=True, choices=[('PROJECT_COLLABORATION', 'Project Collaboration'), ('COLLABORATION_ENERGY', 'Collaboration / Energy'), ('JOB_REQUIREMENT', 'Job Requirement'), ('JUST_BROWSING', 'Just Browsing / Exploring')], max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
