# Generated by Django 6.0.6 on 2026-06-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='app_store_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='google_store_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
