# Generated by Django 6.0.6 on 2026-06-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0002_portfolioitem_app_store_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='website_url',
        ),
    ]
