# Generated by Django 6.0.6 on 2026-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0003_remove_portfolioitem_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='website_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
