# Generated by Django 6.0.6 on 2026-07-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0004_portfolioitem_website_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['index_value', '-created_at']},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='index_value',
            field=models.IntegerField(default=0, help_text='Used to order the portfolio items on the website (e.g. 0, 1, 2, 3)'),
        ),
    ]
