# Generated by Django 6.0.6 on 2026-07-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portfolio', '0005_alter_portfolioitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
