# Generated by Django 6.0.6 on 2026-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_footer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='cookie_policy_link',
            field=models.CharField(blank=True, default='/cookies', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_text',
            field=models.CharField(blank=True, default='@2026 BLACK CUBE SOLUTIONS LLC. All Rights Reserved', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_policy_link',
            field=models.CharField(blank=True, default='/privacy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_conditions_link',
            field=models.CharField(blank=True, default='/terms', max_length=255, null=True),
        ),
    ]
