# Generated by Django 6.0.6 on 2026-06-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_footer', '0002_footer_cookie_policy_link_footer_copyright_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='cookie_policy_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='privacy_policy_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='terms_conditions_link',
        ),
        migrations.AddField(
            model_name='footer',
            name='cookie_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='custom_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_policy_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_conditions_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
