# Generated by Django 6.0.6 on 2026-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_footer', '0003_remove_footer_cookie_policy_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
