# Generated by Django 6.0.6 on 2026-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(default='General', max_length=100)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
